minetest.register_on_newplayer(function(player)
	--print("on_newplayer")
	if minetest.setting_getbool("give_initial_stuff") then
		minetest.log("action", "Giving initial stuff to player "..player:get_player_name())
		player:get_inventory():add_item('main', 'throwing:crossbow')
		player:get_inventory():add_item('main', 'throwing:arrow_obsidian 99')
		player:get_inventory():add_item('main', 'glooptest:kalite_torch 99')
		player:get_inventory():add_item('main', 'ethereal:pick_crystal 1')
		player:get_inventory():add_item('main', 'default:apple 99')
		player:get_inventory():add_item('main', 'ethereal:sword_crystal 1')
		player:get_inventory():add_item('main', 'beds:bed')
		player:get_inventory():add_item('main', 'markers:mark 2')
		player:get_inventory():add_item('main', 'gloopblocks:shovel_evil')
		player:get_inventory():add_item('main', 'ethereal:shovel_crystal')
		player:get_inventory():add_item('main', 'ethereal:axe_crystal')
		player:get_inventory():add_item('main', '3d_armor:chestplate_crystal')
		player:get_inventory():add_item('main', 'shields:shield_crystal')
		player:get_inventory():add_item('main', '3d_armor:leggings_crystal')
		player:get_inventory():add_item('main', '3d_armor:boots_crystal')
		player:get_inventory():add_item('main', '3d_armor:helmet_crystal')
	end
end)

